services:
  database:
    image: mysql:8
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: RapidPay
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminpass

    volumes:
      - db-data:/var/lib/mysql
      - ./scripts/card_details.sql:/docker-entrypoint-initdb.d/1.sql
      - ./scripts/transactions.sql:/docker-entrypoint-initdb.d/2.sql
      - ./scripts/ufe_rates.sql:/docker-entrypoint-initdb.d/3.sql
    ports:
      - 3306:3306

  backend:
    image:  mcr.microsoft.com/dotnet/sdk:8.0
    working_dir: /app
    volumes:
      - ./RapidPay/src:/app
    ports:
      - "5034:5034"
      - "7136:7136"
      - "8080:8080"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1 
    command: ["dotnet", "watch", "run", "--project", "Api", "--urls", "http://0.0.0.0:5034"]
volumes:
  db-data: