services:
  database:
    image: mysql:8
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: RapidPay
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminpass

    volumes:
      - db-data:/var/lib/mysql
      - ./scripts/card_details.sql:/docker-entrypoint-initdb.d/1.sql
      - ./scripts/transactions.sql:/docker-entrypoint-initdb.d/2.sql
    ports:
      - 3306:3306

  backend:
    build:
        context: ./RapidPay
        dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app
      - /app/bin
      - /app/obj
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    command: ["dotnet", "watch", "--project", "MyApi", "run", "--no-launch-profile", "--urls", "http://0.0.0.0:5000"]

volumes:
  db-data: