services:
  database:
    image: mysql:8
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: RapidPay
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminpass

    volumes:
      - db-data:/var/lib/mysql
      - ./scripts/RapidPay_dump.sql:/docker-entrypoint-initdb.d/1.sql
    ports:
      - 3306:3306

  backend:
    image:  mcr.microsoft.com/dotnet/sdk:8.0
    working_dir: /app
    volumes:
      - ./RapidPay/src:/app
    ports:
      - "5034:5034"
      - "7136:7136"
      - "8080:8080"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1 
      - DOTNET_WATCH_RESTART_ON_RUDE_EDIT=true
    command: ["dotnet", "watch", "run", "--project", "Api", "--urls", "http://0.0.0.0:5034"]
volumes:
  db-data: