name: .NET 8 CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SolutionFile: ./RapidPay/RapidPay.sln
      ApiProjectFile: ./RapidPay/src/Api/Api.csproj
      PublishDir: ./publish

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore $SolutionFile

      - name: Build application
        run: dotnet build --configuration Release --no-restore $SolutionFile

      - name: Run tests
        run: dotnet test --configuration Release --no-build --verbosity normal $SolutionFile

      - name: Publish application
        run: dotnet publish $ApiProjectFile -c Release --no-build -o $PublishDir

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: ${{ env.PublishDir }}
